apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: gbdx-scaler
spec:
  maxReplicas: 10
  minReplicas: 2
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: gbdx-deployment
  targetCPUUtilizationPercentage: 50
